feat: use array for passing extra args to llm server
When using double quoted strings for passing extra arguments to llamacpp
server, when empty (verbose=false) the server fails to start with the
error message:

```
error: invalid argument:
```

Because it detects the argument "" (empty string) as an invalid argument
Using bash arrays avoid that problem.

Signed-off-by: Lincoln Wallace <lincoln.wallace@canonical.com>